# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: auth_app_development

test:
  <<: *default
  database: auth_app_test

production:
  <<: *default
  database: auth_app_production
  username: auth_app
  password: <%= ENV['AUTH_APP_DATABASE_PASSWORD'] %>
